name: riverpod_lint
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  custom_lint_builder:
    path: ../custom_lint_builder

  # TODO remove?
  source_gen: ^1.2.1