name: custom_lint_analyzer_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 4.11.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  custom_lint:
    path: /Users/remirousselet/dev/invertase/custom_lint/packages/custom_lint/
